import { useStore } from '../state/store';
import type { Article } from '../types';
import { ultron } from './bridge';

/**
 * News orchestration: fetching (rate-limit aware, handled in main) and the
 * "why this matters to you" pass, which is genuinely generated by the brain -
 * on the fast tier, so the local model does it when it's up and Gemini's
 * quota is saved for real work.
 */

const AUTO_BLURB_COUNT = 5; // top stories get a blurb without being asked
const queue: Article[] = [];
let working = false;

export async function refreshNews(manual = false): Promise<void> {
  const store = useStore.getState();
  if (store.newsLoading) return;
  store.setNews({ loading: true, error: null });

  try {
    const res = await ultron.news.fetch(manual);
    store.setNews({
      articles: res.articles,
      quota: res.quota,
      error: res.error ?? null,
      loading: false,
      lastFetch: res.fetchedAt,
    });
    // Queue the top stories for relevance analysis.
    for (const a of res.articles.slice(0, AUTO_BLURB_COUNT)) enqueueRelevance(a);
  } catch (e) {
    store.setNews({ loading: false, error: e instanceof Error ? e.message : String(e) });
  }
}

export function enqueueRelevance(article: Article): void {
  const store = useStore.getState();
  const existing = store.relevance[article.id];
  if (existing && existing.status !== 'failed') return;
  if (queue.some((q) => q.id === article.id)) return;

  store.setRelevance(article.id, { status: 'pending', text: '' });
  queue.push(article);
  void drain();
}

/**
 * `store.brain` starts null and is only populated once App.tsx's startup
 * probe resolves. Without this wait, "probe still pending" and "confirmed
 * offline" look identical and the first batch after launch gets wrongly
 * marked offline.
 */
async function waitForBrainStatus(timeoutMs = 6000): Promise<ReturnType<typeof useStore.getState>['brain']> {
  const initial = useStore.getState().brain;
  if (initial !== null) return initial;
  return new Promise((resolve) => {
    const timer = setTimeout(() => { unsub(); resolve(useStore.getState().brain); }, timeoutMs);
    const unsub = useStore.subscribe((s) => {
      if (s.brain !== null) { clearTimeout(timer); unsub(); resolve(s.brain); }
    });
  });
}

async function drain(): Promise<void> {
  if (working) return;
  working = true;
  try {
    while (queue.length) {
      const article = queue.shift()!;
      const brain = await waitForBrainStatus();

      // No brain, no blurb - say so rather than inventing one.
      if (!brain?.active) {
        useStore.getState().setRelevance(article.id, {
          status: 'failed',
          text: 'Brain offline - relevance analysis unavailable.',
        });
        continue;
      }

      try {
        const text = await generateRelevance(article);
        useStore.getState().setRelevance(article.id, { status: 'done', text });
      } catch (e) {
        useStore.getState().setRelevance(article.id, {
          status: 'failed',
          text: e instanceof Error ? e.message : String(e),
        });
      }
    }
  } finally {
    working = false;
  }
}

async function generateRelevance(article: Article): Promise<string> {
  const { settings } = useStore.getState();
  const p = settings?.profile;

  const profile = [
    `Location: ${p?.location || 'unspecified'}`,
    `Interests: ${p?.interests?.length ? p.interests.join(', ') : 'unspecified'}`,
    p?.notes ? `Notes: ${p.notes}` : '',
  ].filter(Boolean).join('\n');

  const res = await ultron.brain.once({
    system:
      'You assess why a news story does or does not matter to one specific person. ' +
      'Be concrete and blunt. If the connection is weak, say it is weak rather than inventing one. ' +
      'Reply with one or two sentences, 40 words maximum, no preamble, no markdown, no quotes.',
    user:
      `PERSON\n${profile}\n\n` +
      `STORY\nHeadline: ${article.title}\n` +
      `Summary: ${article.description || article.content || '(none)'}\n` +
      `Region tag: ${article.region}\n\n` +
      'Why does this matter to this person specifically?',
    tier: 'fast',
    temperature: 0.35,
  });
  if (!res.ok) throw new Error(res.error);
  return res.text.replace(/^["'\s]+|["'\s]+$/g, '').slice(0, 400);
}

let timer: ReturnType<typeof setInterval> | null = null;

export function startAutoRefresh(): () => void {
  const mins = useStore.getState().settings?.news.autoRefreshMinutes ?? 60;
  if (timer) clearInterval(timer);
  timer = setInterval(() => { void refreshNews(false); }, Math.max(15, mins) * 60_000);
  return () => { if (timer) clearInterval(timer); timer = null; };
}
